import React from 'react';
import {
  Wind, Wifi, Coffee, Car, Tv, Utensils,
  Waves, Thermometer, Shield, Clock, Sun,
  Pocket as Pool, Bath, Bed, User, Home,
  Key, MapPin, Phone, Star, Check, X,
  Trash2, Search, Heart, Share2, Calendar,
  ChevronRight, ChevronLeft, ArrowRight,
  Menu, Info, AlertTriangle, CheckCircle2,
  Lock, CreditCard, Laptop, Radio, Music,
  Mic, Camera, Speaker, Tablet, Smartphone,
  Power, Zap, Droplets, Flame, Cloud,
  CloudRain, CloudLightning, Snowflake,
  WashingMachine, Refrigerator, LayoutGrid,
  Map as MapIcon, Users
} from 'lucide-react';
import { AmenityCode, PropertyType } from '../../../packages/shared/types';

/**
 * Horus Zenith - 100% Coverage Amenity Mapping
 */
export const AmenityIcons: Record<string, React.ElementType> = {
  'ACCESSIBLE_HEIGHT_BED': Bed,
  'ACCESSIBLE_HEIGHT_TOILET': Bath,
  'AIR_CONDITIONING': Wind,
  'BABYSITTER_RECOMMENDATIONS': Users,
  'BABY_BATH': Bath,
  'BABY_MONITOR': Mic,
  'BATHTUB': Bath,
  'BBQ_GRILL': Flame,
  'BEACH_ESSENTIALS': Sun,
  'BED_LINENS': Bed,
  'BREAKFAST': Coffee,
  'CABLE_TV': Tv,
  'CARBON_MONOXIDE_DETECTOR': Shield,
  'CHANGING_TABLE': User,
  'CHILDREN_BOOKS_AND_TOYS': Smartphone,
  'CHILDREN_DINNERWARE': Utensils,
  'CLEANING_BEFORE_CHECKOUT': Clock,
  'COFFEE_MAKER': Coffee,
  'COOKING_BASICS': Utensils,
  'DISABLED_PARKING_SPOT': Car,
  'DISHES_AND_SILVERWARE': Utensils,
  'DISHWASHER': Droplets,
  'DOGS': Heart,
  'DOORMAN': User,
  'DRYER': Wind,
  'ELEVATOR_IN_BUILDING': ArrowRight,
  'ESSENTIALS': Check,
  'EV_CHARGER': Zap,
  'EXTRA_PILLOWS_AND_BLANKETS': Bed,
  'FIREPLACE_GUARDS': Shield,
  'FIRE_EXTINGUISHER': Shield,
  'FIRM_MATTRESS': Bed,
  'FIRST_AID_KIT': Shield,
  'FLAT_SMOOTH_PATHWAY_TO_FRONT_DOOR': MapPin,
  'FREE_PARKING_ON_PREMISES': Car,
  'GAME_CONSOLE': Smartphone,
  'GARDEN_OR_BACKYARD': Sun,
  'GRAB_RAILS_FOR_SHOWER_AND_TOILET': Shield,
  'GYM': Zap,
  'HAIR_DRYER': Wind,
  'HANGERS': Check,
  'HEATING': Thermometer,
  'HIGH_CHAIR': User,
  'HOT_TUB': Waves,
  'HOT_WATER': Droplets,
  'INDOOR_FIREPLACE': Flame,
  'INTERNET': Wifi,
  'IRON': Zap,
  'KITCHEN': Utensils,
  'LAPTOP_FRIENDLY_WORKSPACE': Laptop,
  'LONG_TERM_STAYS_ALLOWED': Calendar,
  'LUGGAGE_DROPOFF_ALLOWED': Clock,
  'MICROWAVE': Utensils,
  'OTHER_PET': Heart,
  'OUTLET_COVERS': Shield,
  'OVEN': Utensils,
  'PACK_N_PLAY_TRAVEL_CRIB': Bed,
  'PATH_TO_ENTRANCE_LIT_AT_NIGHT': Sun,
  'PATIO_OR_BALCONY': Sun,
  'PETS_ALLOWED': Heart,
  'PETS_LIVE_ON_THIS_PROPERTY': Heart,
  'POCKET_WIFI': Wifi,
  'PRIVATE_ENTRANCE': Key,
  'REFRIGERATOR': Refrigerator,
  'ROLL_IN_SHOWER_WITH_SHOWER_BENCH_OR_CHAIR': Bath,
  'ROOM_DARKENING_SHADES': Snowflake,
  'SHAMPOO': Droplets,
  'SINGLE_LEVEL_HOME': Home,
  'SMOKE_DETECTOR': Shield,
  'SMOKING_ALLOWED': Info,
  'STAIR_GATES': Shield,
  'STEP_FREE_ACCESS': ArrowRight,
  'STOVE': Utensils,
  'SUITABLE_FOR_INFANTS': User,
  'SUITABLE_FOR_CHILDREN': Users,
  'TUB_WITH_SHOWER_BENCH': Bath,
  'TV': Tv,
  'WASHER': WashingMachine,
  'WIDE_CLEARANCE_TO_BED': Bed,
  'WIDE_CLEARANCE_TO_SHOWER_AND_TOILET': Bath,
  'WIDE_DOORWAY': Home,
  'WIDE_HALLWAY_CLEARANCE': Home,
  'WINDOW_GUARDS': Shield,
  'WIRELESS_INTERNET': Wifi,
};

export const PropertyTypeIcons: Record<string, React.ElementType> = {
  'APARTMENT': Home,
  'HOUSE': Home,
  'LOFT': Home,
  'BOAT': Waves,
  'CAMPER_RV': Car,
  'CONDOMINIUM': Home,
  'BED_AND_BREAKFAST': Coffee,
  'CABIN': Home,
  'TOWNHOUSE': Home,
  'HUT': Home,
  'DORM': Users,
  'TREEHOUSE': Sun,
  'YURT': Sun,
  'CASTLE': Shield,
  'STUDIO': Home,
  'BUNGALOW': Home,
  'CHALET': Snowflake,
  'VILLA': Home,
  'TENT': Sun,
};

export const SectionIcons: Record<string, React.ElementType> = {
  'hero': LayoutGrid,
  'featureGrid': Grid,
  'testimonialList': MessageSquare,
  'propertyHighlight': Star,
  'areaGuide': MapIcon,
  'faq': MessageSquare,
  'richText': Type,
  'ctaBanner': Megaphone,
  'logoCloud': Grid,
  'pricingTable': CreditCard,
  'comparisonTable': LayoutGrid,
  'howItWorks': CheckCircle2,
  'propertyCollection': Star,
  'statsBand': Star,
  'newsletter': Mail,
};
